### ISSUE TITLE
📄 Missing time API in pogobot documentation

### ISSUE THREAD

**Issue by White-On** [nekonaute/pogobot#3]
# Missing time API in pogobot documentation
It seems like the robot API documentation is missing the time tools provided in the [pogobot_timer_sleep_stopwatch.c](https://github.com/nekonaute/pogobot/blob/c05bc139d06b2061d2ae6966490c20e5dee9bd12/Software/pogolib/pogobot_timer_sleep_stopwatch.c).

**Comment by White-On** [comment]
I've added a PR to try updating the robot API #4 hopefully helping. Have a nice day 😉

**Comment by alexguersu** [comment]
Thank you for noticing it. :)
I will modify pogobot.h to integrate the timer API and generate the docs.

**Comment by alexguersu** [comment]
Thank you for noticing it. :)
I will modify pogobot.h to integrate the timer API and generate the docs.

**Comment by alexguersu** [comment]
Everything is upgraded in commit ea1596a
